### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by Demomaker** [Hopson97/open-builder#85]
I followed all the steps from the Building (Visual Studio) guide for Windows to be able to contribute to the project, but I still get errors while trying to compile the project.

I am getting a C1189  "#error : 'unsupported Lua version (i.e. not Lua 5.1, 5.2, 5.3)'" .
The C1189 error leads to this part of the code in deps/sol.hpp : 
![image](https://user-images.githubusercontent.com/18319764/72671361-f27a1500-3a16-11ea-9e66-e0623b4acdbb.png)

I am also getting a C2679  "binary '<<' : no operator found accepts a right operand of type 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (or there is no acceptable conversion)".
The C2679 error leads to this part of the code in deps/sol.hpp :
![image](https://user-images.githubusercontent.com/18319764/72671343-bf378600-3a16-11ea-9fd8-4230aba3f954.png)

I tried to follow the Building (Visual Studio) guide for Windows as closely as possible, but I'm still getting these errors. Am I missing something?

**Comment by Hopson97** [comment]
Ah apolgies about this, I forgot to update the documentation after adding lua to the game.

The fix for the lua issue to add the `deps/lua/` folder as an Additional Include Directory for both configurations. 

As for the other error you mention with the `std::cout`, that should also be solved by this.

**Comment by Demomaker** [comment]
I added the deps/lua/ folder as an Additional Include Directory for both configurations.
It solved the lua issue, but didn't solve the std::cout issue and there is now a C3779 error : 
"'sol::stack::stack_detail::unchecked_unqualified_get' : a function that sends 'decltype(auto)' can not be used before being defined"
The error points to this in deps/sol.hpp : 
![image](https://user-images.githubusercontent.com/18319764/72671496-5ac9f600-3a19-11ea-89de-0d671383e08b.png)

**Comment by Hopson97** [comment]
You may have missed the adding C++17 , step 5.

Not sure what else would have been missed apart from this.

**Comment by Demomaker** [comment]
I do have the step 5 done : 
![image](https://user-images.githubusercontent.com/18319764/72671618-14759680-3a1b-11ea-90a1-54d2ce74d9e6.png)
(It is in french but it's basically saying ISO C++17 Standard)
Although, I dont know why, the option is not present in "Configuration Properties -> General".
I could only find it in "Configuration Properties -> C/C++ -> All options".
I don't know if the fact that I have Visual Studio 2017 changes anything.

**Comment by Demomaker** [comment]
Could it be because I chose a "Visual C++" Empty project?
I can't seem to find a setting for a "C/C++" Empty project.

**Comment by Hopson97** [comment]
Not sure about this one, I have asked on my discord server though, so cannot help for the time being, sorry :(

**Comment by Hopson97** [comment]
I mean it could be different versionings causing this.

As for the cout issue, you could double-check that `#include <string>` is at the top of the file, but not sure about the issue with sol

**Comment by Demomaker** [comment]
Adding #include <string> at the top of the std::cout error's file did solve the std::cout issue, but the other issue is still there. Also, thank you so much for trying to help me with this.

**Comment by Hopson97** [comment]
Ahh found it!

https://github.com/ThePhD/sol2/issues/830

Seems if you remove the /permissive flag (I guess visual studio 2017 adds it by default?) then it should work :)

**Comment by Demomaker** [comment]
Yay, it worked! Thank you so much for helping me :D. 
The project compiles now.

**Comment by Hopson97** [comment]
Awesome! If it doesn't run, try building/running using the release configuration, as the debug one tends to be quite hit and miss.

**Comment by Demomaker** [comment]
It does work with release. I tried with debug, but it just shows a white screen.
